{
 "title": "GCP Asset Inventory",
 "description": "This  dashboard provides a high level view of all your Google Cloud Platform resources across all accounts accounts and regions",
 "tags": [
  "cloud-inventory",
  "gcp",
  "postgres",
  "inventory",
  "banshee"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_ids",
    "label": "project_ids",
    "query": "select distinct(project_id) from gcp_resources"
   },
   {
    "name": "cq_tables",
    "label": "cq_tables",
    "query": "select distinct(_cq_table)  as _cq_table from gcp_resources where _cq_table not in ('gcp_machine_types', 'gcp_compute_machine_types', 'gcp_compute_disk_types', 'gcp_compute_zones') order by _cq_table asc;"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Resources",
     "type": "stat",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from gcp_resources where project_id in (${project_ids}) and _cq_table in (${cq_tables})"
      }
     ]
    },
    {
     "title": "Total Resource by Account",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 7, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select project_id, count(*) from gcp_resources where _cq_table in ($cq_tables) and project_id in ($project_ids) group by project_id order by count desc"
      }
     ]
    },
    {
     "title": "Resource Type",
     "type": "table",
     "gridPos": { "h": 11, "w": 9, "x": 14, "y": 1 },
     "targets": [
      {
       "rawSql": "select _cq_table, count(*) from gcp_resources where project_id in ($project_ids) and _cq_table in ($cq_tables) and _cq_table not in ('gcp_compute_machine_types', 'gcp_compute_disk_types', 'gcp_compute_zones')  group by _cq_table order by count desc"
      }
     ]
    },
    {
     "title": "All Resources",
     "type": "table",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "select \n*\nfrom gcp_resources \nwhere project_id in ($project_ids) and _cq_table in ($cq_tables)\norder by project_id asc, name asc;"
      }
     ]
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Network (VPC) List ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\nproject_id, name, ipv4_range, description\nFROM gcp_compute_networks\nWHERE\n  project_id IN ($project_ids)\nORDER BY project_id asc"
    }
   ]
  },
  {
   "title": "Subnet List",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\nsn.project_id,n.name as vpc_name,sn.name subnet_name,sn.gateway_address,sn.ip_cidr_range,sn.description,sn.enable_flow_logs,sn.private_ip_google_access,sn.creation_timestamp,sn.purpose\nFROM gcp_compute_subnetworks sn\nLEFT OUTER JOIN gcp_compute_networks n\nON sn.network = n.self_link \nWHERE\n  sn.project_id IN ($project_ids)\nORDER BY sn.project_id asc, sn.ip_cidr_range asc, sn.name asc"
    }
   ]
  },
  {
   "title": "VPC Peering List",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n\tproject_id, \n\tname as vpc_name,\n\tjsonb_array_elements(peerings) -> 'name' as peering_name,\n\tjsonb_array_elements(peerings) -> 'network' as network,\t\n\tjsonb_array_elements(peerings) -> 'auto_create_routes' as auto_create_routes,\n\tjsonb_array_elements(peerings) -> 'exchange_subnet_routes' as exchange_subnet_routes,\n\tjsonb_array_elements(peerings) -> 'export_custom_routes' as export_custom_routes,\n\tjsonb_array_elements(peerings) -> 'export_subnet_routes_with_public_ip' as export_subnet_routes_with_public_ip,\n\tjsonb_array_elements(peerings) -> 'import_custom_routes' as import_custom_routes,\n\tjsonb_array_elements(peerings) -> 'import_subnet_routes_with_public_ip' as import_subnet_routes_with_public_ip,\n\tjsonb_array_elements(peerings) -> 'peer_mtu' as peer_mtu,\n\tjsonb_array_elements(peerings) -> 'stack_type' as stack_type,\n\tjsonb_array_elements(peerings) -> 'state' as state,\n\tjsonb_array_elements(peerings) -> 'state_details' as state_details\nFROM gcp_compute_networks\nWHERE project_id IN ($project_ids)\nORDER BY project_id ASC, vpc_name ASC, peering_name ASC;"
    }
   ]
  },
  {
   "title": "Compute Instance - Public IP List",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT project_id, name, address, network_tier, address_type, purpose, status\nFROM gcp_compute_addresses\nWHERE address_type='EXTERNAL' AND project_id IN ($project_ids)\nORDER BY project_id ASC, address ASC, status DESC"
    }
   ]
  },
  {
   "title": "Compute Instance - Private IP List",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT project_id, name, address, network_tier, address_type, purpose, status\nFROM gcp_compute_addresses\nWHERE address_type='INTERNAL' AND project_id IN ($project_ids)\nORDER BY project_id ASC, address ASC, status DESC"
    }
   ]
  },
  {
   "title": "Compute Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance List",
     "type": "table",
     "description": "List of Compute Instances",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n\ts.project_id,\n\ts.creation_timestamp as created_at,\n\ts.\"name\",\n\ts.hostname,\n\ts.description,\n\ts.status,\n\tservice_accountx::jsonb->>'email' as service_account,\n\tni::jsonb->>'network_i_p' as private_ip,\n\tjsonb_array_elements((ni::jsonb->>'access_configs')::jsonb)->>'nat_i_p' as public_ip,\n\ts.cpu_platform,\n\ts.can_ip_forward::bool,\n\ts.deletion_protection::bool,\n\t(s.scheduling->>'preemtible')::bool as preemtible,\n\t(s.advanced_machine_features::jsonb->>'threads_per_core') as threads_per_core,\n\t(s.advanced_machine_features::jsonb->>'visible_core_count') as visible_core_count,\n\ts.machine_type,\n\ts.\"zone\"\nFROM\n\tgcp_compute_instances s,\n\tjsonb_array_elements(s.service_accounts) as service_accountx,\n\tjsonb_array_elements(network_interfaces) as ni\nWHERE project_id IN ($project_ids)\nORDER BY \n\ts.project_id asc,\n\ts.\"name\" asc,\n\ts.status asc\n"
      }
     ]
    }
   ]
  },
  {
   "title": "CloudSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count Postgre Database by Version",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  COUNT(_cq_id) AS \"_COUNT\",\n  database_installed_version\nFROM\n  gcp_sql_instances\nWHERE\n  database_version LIKE 'POSTGRES%'\n  AND \n  project_id IN ($project_ids)\nGROUP BY\n  database_installed_version\nLIMIT\n  50"
      }
     ]
    },
    {
     "title": "CloudSQL Instances",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\n  _cq_sync_time AS \"time\",\n  project_id,\n  gce_zone AS zone,\n  name,\n  database_version,\n  failover_replica,\n  instance_type,\n  (ip_addresses->0->>'ipAddress') AS primary_ip_address,\n  ip_addresses,\n  create_time\nFROM gcp_sql_instances\nWHERE \n  ip_addresses @> '[{\"type\": \"PRIMARY\"}]'\n  AND \n  project_id IN ($project_ids)\nORDER BY project_id ASC, name asc;"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud Storage - Bucket",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT\n\ts.project_id,  \n  \ts.\"name\" ,\n  \ts.storage_class,\n  \ts.\"location\",\n\t\ts.\"location_type\",\n  \t(s.bucket_policy_only::jsonb) ->> 'Enabled' as bucket_policy_only,\n  \t(s.uniform_bucket_level_access::jsonb) ->> 'Enabled' as uniform_bucket_level_access,\n  \ts.public_access_prevention,\n  \ts.default_event_based_hold,\n  \ts.versioning_enabled::bool \nFROM\n  gcp_storage_buckets as s\nWHERE project_id IN ($project_ids)\nORDER BY s.project_id ASC,  \n  \ts.\"name\" ASC"
      }
     ]
    }
   ]
  }
 ]
}